language: minimal

sudo: false

dist: trusty

git:
  submodules: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:adrozdoff/emacs'
    packages:
    - emacs25

script:
  - emacs --version
  - ./tools/test-indentation
