language: minimal

sudo: false

dist: trusty

git:
  submodules: false

addons:
  apt:
    sources:
      - sourceline: 'ppa:kelleyk/emacs'
    packages:
      - emacs25

before_install:
  - mkdir -p $HOME/emacs24 $HOME/emacs25
  - ln -s $(which emacs24) $HOME/emacs24/emacs
  - ln -s $(which emacs25) $HOME/emacs25/emacs

matrix:
  include:
    - env: PATH=$HOME/emacs24:$PATH
    - env: PATH=$HOME/emacs25:$PATH

script:
  - emacs --version
  - ./tools/test-indentation
