name: CI

on:
  pull_request:
    branches: [ master ]

  push:
    branches: [ master ]

jobs:
  test-on-nightly:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Install dependencies
      run: |
        sudo apt install emacs

    - name: Check Emacs version
      run: emacs --version

    - name: Test indentation
      run: tools/test-indentation
